# Generated by Django 5.1.6 on 2025-08-01 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='phone',
        ),
    ]
