# Generated by Django 5.2.5 on 2025-09-17 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_visit_builder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='builder',
        ),
    ]
