# Generated by Django 5.2.5 on 2025-09-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_visit_builder'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('sold', 'Sold')], default='pending', max_length=50),
        ),
    ]
