# Generated by Django 5.2.5 on 2025-09-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('sold', 'Sold')], default='pending', max_length=50),
        ),
    ]
